[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi=true
verbosity=5
openzeppelin-contracts = { path = "lib/openzeppelin-contracts"}
remmaping = [[
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@arachnid/=lib/solidity-stringutils/src/",
]]